# -*- coding: utf-8 -*-
"""Datos base para planilla de auditoría técnico-ambiental - Instalación Río Ventisquero."""

CONTRATO = (
    "Terminación Mejoramiento Ruta 7 Norte Etapa II Pavimentación, "
    "sector Fiordo Queulat–Puente Chucao, tramo km 415,889 a km 433,193, "
    "comuna de Cisnes, provincia de Aysén, Región de Aysén"
)
INSTALACION = "Instalación de Faenas Río Ventisquero"
EMPRESA = "Constructora APIA SpA"
MANDANTE = "Validar con mandante / Inspección Fiscal"
REGION = "Región de Aysén"
COMUNA = "Comuna de Cisnes"
PLAN_MANEJO = "Plan de Manejo Ambiental Específico para Instalación de Faenas Río Ventisquero, Rev. 1"
VERSION_ARCHIVO = "1.0"

LISTAS = {
    "componente": [
        "Autorizaciones y permisos", "Condiciones generales de operación", "Orden y limpieza",
        "Ocupación del área", "Control de accesos", "Flujo y tránsito de maquinaria",
        "Velocidad máxima", "Funcionamiento de motores", "Emisiones atmosféricas",
        "Polvo y material particulado", "Ruido", "Generador eléctrico", "Combustibles",
        "Sustancias peligrosas", "Derrames y contingencias", "Mantención mecánica",
        "Protección del suelo", "Protección del agua", "Río Ventisquero", "Baños químicos",
        "Fosas sépticas", "Agua potable", "Agua envasada", "Residuos domiciliarios y asimilables",
        "Residuos industriales no peligrosos", "Residuos peligrosos", "Bodega RESPEL",
        "Patio de salvataje", "Segregación de residuos", "Transporte y disposición final",
        "Declaración RCD", "Declaración anual de emisiones", "Control de plagas",
        "Sanitización y desratización", "Flora y fauna", "Prohibición de caza y alimentación de fauna",
        "Patrimonio arqueológico", "Relaciones con la comunidad", "ZOIT Aysén Patagonia Queulat",
        "Señalización", "Horarios de trabajo", "Contratación de mano de obra local",
        "Capacitación e inducción ambiental", "Control documental", "Abandono y cierre de la instalación",
    ],
    "estado_cumplimiento": [
        "Cumple", "Cumple parcialmente", "No cumple", "No aplica",
        "Pendiente de verificación", "En proceso de regularización",
    ],
    "nivel_hallazgo": ["Crítico", "Mayor", "Menor", "Observación", "Buena práctica", "Sin hallazgo"],
    "estado_hallazgo": ["Abierto", "En tratamiento", "Cerrado", "Verificado", "Reabierto"],
    "tipo_evidencia": [
        "Fotografía", "Acta", "Certificado", "Resolución", "Guía de transporte",
        "Manifiesto", "Informe", "Registro", "Lista de asistencia", "Libro de Comunicaciones", "Otro",
    ],
    "frecuencia": ["Diaria", "Semanal", "Quincenal", "Mensual", "Trimestral", "Semestral", "Anual", "Eventual"],
    "etapa": ["Instalación", "Operación", "Mantenimiento", "Cierre", "Todas las etapas"],
    "tipo_obligacion": [
        "Obligación contenida en el Plan de Manejo",
        "Exigencia legal o reglamentaria",
        "Compromiso contractual",
        "Buena práctica ambiental",
        "Antecedente documental pendiente",
    ],
    "nivel_certeza": [
        "Expreso en el Plan de Manejo",
        "Derivado del Plan de Manejo",
        "Norma o permiso aplicable",
        "Requiere validación",
    ],
    "si_no": ["Sí", "No"],
    "estado_documental": [
        "Vigente", "Por vencer en 30 días", "Por vencer en 60 días",
        "Vencido", "En trámite", "No disponible", "No aplica",
    ],
    "tipo_residuo": [
        "Residuos domiciliarios", "RCD", "Chatarra", "Madera", "Plásticos no contaminados",
        "Aceite usado", "Filtros", "Baterías", "Ropa contaminada", "Tierra contaminada",
        "Huaipe", "Envases contaminados", "Tubos fluorescentes", "Otros RESPEL",
    ],
    "unidad": ["kg", "ton", "m³", "L", "unidad", "bolsa", "contenedor"],
    "riesgo_ambiental": ["Alto", "Medio", "Bajo", "No aplica"],
    "responsables": [
        "Encargado ambiental", "Administrador de obra", "Jefe de faena",
        "Supervisor de área", "Inspector Fiscal", "Contratista RESPEL", "Otro",
    ],
}

# (id, componente, subcomponente, etapa, area, requisito, medida, fuente, norma, frecuencia,
#  indicador, metodo, resultado_esperado, tipo_obligacion, nivel_certeza, ponderacion)
REQUISITOS = [
    ("REQ-001", "Autorizaciones y permisos", "Plan de Manejo", "Operación", "Oficina ambiental",
     "Disponibilidad del PMA aprobado Rev. 1", "Mantener PMA aprobado disponible para fiscalización",
     PLAN_MANEJO, "Validar con normativa vigente o autoridad competente", "Mensual",
     "Documento vigente y accesible", "Revisión documental", "PMA Rev. 1 disponible y legible",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-002", "Autorizaciones y permisos", "Agua potable", "Operación", "Sistema AP",
     "Autorización sistema de agua potable particular", "Contar con aprobación sanitaria del sistema AP",
     PLAN_MANEJO, "DS 594 / Validar con SEREMI de Salud", "Mensual",
     "Resolución o certificado vigente", "Revisión documental", "Autorización vigente disponible",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-003", "Autorizaciones y permisos", "Alcantarillado", "Operación", "Sistema AS",
     "Autorización sistema de alcantarillado particular", "Contar con aprobación del sistema AS",
     PLAN_MANEJO, "Validar con SEREMI de Salud", "Mensual",
     "Resolución vigente", "Revisión documental", "Autorización disponible y vigente",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-004", "Autorizaciones y permisos", "Bodega RESPEL", "Operación", "Bodega RESPEL",
     "Autorización bodega de residuos peligrosos", "Bodega RESPEL autorizada por autoridad competente",
     PLAN_MANEJO, "DS 148 / Validar con autoridad competente", "Mensual",
     "Autorización vigente en sitio", "Inspección y revisión documental", "Autorización RESPEL vigente",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-005", "Autorizaciones y permisos", "Residuos no peligrosos", "Operación", "Patio de salvataje",
     "Autorización bodega/patio residuos no peligrosos", "Patio o bodega autorizada para RNP",
     PLAN_MANEJO, "Validar con normativa vigente o autoridad competente", "Mensual",
     "Resolución o antecedente disponible", "Revisión documental", "Autorización disponible",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-006", "Autorizaciones y permisos", "Control de plagas", "Operación", "Instalación completa",
     "Resolución sanitaria control de plagas", "Servicio de control de plagas con resolución sanitaria",
     PLAN_MANEJO, "Validar con SEREMI de Salud", "Mensual",
     "Resolución vigente del prestador", "Revisión documental", "Resolución sanitaria vigente",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-007", "Autorizaciones y permisos", "Baños y fosas", "Operación", "Sanitarios",
     "Autorización limpieza baños químicos y fosas sépticas", "Empresa autorizada para servicios sanitarios",
     PLAN_MANEJO, "Validar con SEREMI de Salud", "Mensual",
     "Certificado/resolución del prestador", "Revisión documental", "Autorización sanitaria vigente",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-008", "Autorizaciones y permisos", "Agua envasada", "Operación", "Comedor/bodega",
     "Autorización proveedor agua envasada", "Proveedor con autorización sanitaria",
     PLAN_MANEJO, "Validar con SEREMI de Salud", "Mensual",
     "Certificado vigente", "Revisión documental", "Autorización disponible",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-009", "Autorizaciones y permisos", "Alimentación", "Operación", "Comedor",
     "Autorización servicio de alimentación", "Servicio de alimentación autorizado",
     PLAN_MANEJO, "Validar con SEREMI de Salud", "Mensual",
     "Resolución sanitaria vigente", "Revisión documental", "Autorización vigente",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-010", "Autorizaciones y permisos", "Laboratorio", "Operación", "Laboratorio",
     "Autorización o antecedentes del laboratorio", "Laboratorio con respaldo documental",
     PLAN_MANEJO, "Validar con normativa vigente o autoridad competente", "Mensual",
     "Antecedentes disponibles", "Revisión documental", "Documentación disponible",
     "Antecedente documental pendiente", "Requiere validación", 1),
    ("REQ-011", "Autorizaciones y permisos", "Equipos radiactivos", "Operación", "Bunker/laboratorio",
     "Autorización bunker o almacenamiento equipos radiactivos", "Si aplica, contar con autorización CCHEN",
     PLAN_MANEJO, "Validar con CCHEN si aplica", "Mensual",
     "Autorización o declaración de no aplicabilidad", "Revisión documental", "Cumplimiento o N/A documentado",
     "Antecedente documental pendiente", "Requiere validación", 1),
    ("REQ-012", "Autorizaciones y permisos", "Grupo generador", "Operación", "Planta eléctrica",
     "Certificados y antecedentes del grupo generador", "Documentación técnica y operacional del generador",
     PLAN_MANEJO, "Validar con normativa vigente o autoridad competente", "Mensual",
     "Certificados disponibles", "Revisión documental e inspección", "Antecedentes completos",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-013", "Declaración anual de emisiones", "RETC", "Operación", "Oficina ambiental",
     "Declaración emisiones atmosféricas RETC", "Declarar emisiones cuando corresponda (ene-abr 2027)",
     PLAN_MANEJO, "Ley 19.300 / RETC MMA", "Anual",
     "Declaración presentada en plazo", "Revisión RETC", "Declaración presentada o planificado",
     "Exigencia legal o reglamentaria", "Norma o permiso aplicable", 1),
    ("REQ-014", "Autorizaciones y permisos", "Combustibles", "Operación", "Estanque combustible",
     "Autorización transporte de combustibles", "Transportista y operación con respaldo legal",
     PLAN_MANEJO, "Validar con normativa vigente o autoridad competente", "Mensual",
     "Autorizaciones del transportista", "Revisión documental", "Documentos vigentes",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-015", "Control documental", "Libro de Comunicaciones", "Operación", "Oficina de obra",
     "Registro entrega documental al mandante", "Comunicaciones al mandante vía Libro de Comunicaciones",
     PLAN_MANEJO, "Bases contractuales", "Mensual",
     "Folio registrado", "Revisión Libro de Comunicaciones", "Comunicaciones registradas",
     "Compromiso contractual", "Derivado del Plan de Manejo", 1),
    ("REQ-016", "Emisiones atmosféricas", "Vehículos", "Operación", "Accesos y vías internas",
     "Estado técnico de camionetas, camiones y maquinaria", "Equipos con revisión técnica y permisos vigentes",
     PLAN_MANEJO, "Validar normativa vehicular vigente", "Mensual",
     "Permisos y revisión al día", "Inspección visual y revisión documental", "Sin emisiones visibles anómalas",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-017", "Emisiones atmosféricas", "Control operacional", "Operación", "Instalación completa",
     "Control de emisiones visibles", "Ausencia de humo visible anormal en equipos",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Sin humo negro persistente", "Inspección visual", "Emisiones controladas",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-018", "Polvo y material particulado", "Control de polvo", "Operación", "Accesos y caminos",
     "Control de polvo en accesos y caminos", "Riego con camión aljibe cuando corresponda",
     PLAN_MANEJO, PLAN_MANEJO, "Diaria",
     "Polvo controlado en vías transitadas", "Inspección visual", "Polvo mitigado",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-019", "Polvo y material particulado", "Transporte", "Operación", "Acceso Ruta 7",
     "Uso de mallas o lonas en camiones", "Carga cubierta en transporte de material",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Cargas cubiertas", "Inspección visual", "Sin material suelto en tránsito",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-020", "Velocidad máxima", "Control vehicular", "Operación", "Vías internas y acceso",
     "Cumplimiento límite de velocidad", "Respeto de velocidad máxima señalizada",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Velocidad ≤ límite autorizado", "Inspección y observación", "Cumplimiento verificado",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-021", "Combustibles", "Registro", "Operación", "Estanque/combustible",
     "Registro consumo mensual de combustible", "Registro mensual para gestión y declaraciones",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Registro completo del mes", "Revisión de registros", "Registro actualizado",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-022", "Generador eléctrico", "Operación", "Operación", "Planta eléctrica",
     "Horas de funcionamiento del generador", "Registro de horas de operación",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Registro de horas disponible", "Revisión de bitácora", "Horas registradas",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-023", "Generador eléctrico", "Potencia", "Operación", "Planta eléctrica",
     "Potencia del generador registrada", "Antecedente técnico coherente con operación",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Dato de potencia disponible", "Revisión documental", "Información disponible",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-024", "Ruido", "Horarios", "Operación", "Instalación completa",
     "Cumplimiento horario de trabajo", "Actividades dentro del horario autorizado",
     PLAN_MANEJO, "Validar con normativa vigente o autoridad competente", "Semanal",
     "Sin actividades fuera de horario", "Inspección y registro", "Horario respetado",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-025", "Ruido", "Generador", "Operación", "Planta eléctrica",
     "Estado y ubicación del grupo generador", "Generador en sector autorizado con mitigación",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Ubicación conforme al PMA", "Inspección visual", "Generador correctamente emplazado",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-026", "Ruido", "Mitigación", "Operación", "Instalación completa",
     "Medidas de mitigación acústica", "Implementación de medidas del PMA",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Medidas implementadas", "Inspección visual", "Mitigación operativa",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-027", "Ruido", "Reclamos", "Operación", "Comunidad",
     "Reclamos o denuncias por ruido", "Registro y respuesta a reclamos",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Registro de reclamos y acciones", "Revisión documental", "Reclamos gestionados",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-028", "Protección del suelo", "Superficies", "Operación", "Estanques/taller",
     "Existencia de superficies impermeables", "Radier o superficies impermeabilizadas",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Superficies en buen estado", "Inspección visual", "Impermeabilización operativa",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-029", "Sustancias peligrosas", "Contención", "Operación", "Bodega combustible/taller",
     "Uso de bandejas de contención", "Bandejas bajo estanques y equipos",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Bandejas instaladas y limpias", "Inspección visual", "Contención secundaria operativa",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-030", "Derrames y contingencias", "Kit derrames", "Operación", "Taller/estanque",
     "Disponibilidad kit para derrames", "Kit completo y accesible",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Kit completo y vigente", "Inspección física", "Kit operativo",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-031", "Sustancias peligrosas", "Señalización", "Operación", "Bodegas y estanques",
     "Señalización de sustancias peligrosas", "Señalética conforme a normativa",
     PLAN_MANEJO, "Validar con normativa vigente o autoridad competente", "Mensual",
     "Señalización visible y legible", "Inspección visual", "Señalización adecuada",
     "Exigencia legal o reglamentaria", "Norma o permiso aplicable", 1),
    ("REQ-032", "Sustancias peligrosas", "HDS", "Operación", "Bodegas químicas/RESPEL",
     "Hojas de Datos de Seguridad disponibles", "HDS para sustancias almacenadas",
     PLAN_MANEJO, "DS 594 / DS 43", "Mensual",
     "HDS disponibles y actuales", "Revisión documental", "HDS accesibles",
     "Exigencia legal o reglamentaria", "Norma o permiso aplicable", 1),
    ("REQ-033", "Combustibles", "Carga/descarga", "Operación", "Estanque combustible",
     "Control de carga y descarga de combustibles", "Procedimiento sin derrames",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Operación controlada", "Inspección visual", "Sin derrames en operación",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-034", "Mantención mecánica", "Área taller", "Operación", "Taller mecánico",
     "Condiciones del área de mantención mecánica", "Taller ordenado con protección de suelo",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Área limpia y contenida", "Inspección visual", "Taller conforme",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-035", "Protección del suelo", "Geotextil", "Operación", "Taller/estanque",
     "Existencia de geotextil o equivalente", "Protección adicional del suelo",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Geotextil en buen estado", "Inspección visual", "Protección implementada",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-036", "Protección del suelo", "Contaminación", "Operación", "Instalación completa",
     "Ausencia de manchas, derrames o contaminación", "Sin evidencia de contaminación de suelo",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Sin manchas ni olores anómalos", "Inspección visual", "Suelo sin contaminación visible",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-037", "Derrames y contingencias", "Procedimiento", "Operación", "Instalación completa",
     "Aplicación procedimiento de contingencias", "Procedimiento conocido y aplicable",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Procedimiento disponible y difundido", "Revisión documental e inducción", "Procedimiento operativo",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-038", "Derrames y contingencias", "Incidentes", "Operación", "Instalación completa",
     "Registro de incidentes ambientales", "Registro y reporte de incidentes",
     PLAN_MANEJO, "Ley 19.300 / RCA si aplica", "Mensual",
     "Registro actualizado", "Revisión de registros", "Incidentes registrados y gestionados",
     "Exigencia legal o reglamentaria", "Norma o permiso aplicable", 1),
    ("REQ-039", "Agua potable", "Estanques", "Operación", "Sistema AP",
     "Condiciones de estanques de agua potable", "Estanques limpios, protegidos y señalizados",
     PLAN_MANEJO, "DS 594", "Mensual",
     "Estanques conformes", "Inspección visual", "Estanques en buen estado",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-040", "Agua potable", "Cloración", "Operación", "Sistema AP",
     "Funcionamiento del sistema de cloración", "Cloración operativa según procedimiento",
     PLAN_MANEJO, "DS 594", "Semanal",
     "Sistema operativo", "Inspección y registro", "Cloración activa",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-041", "Agua potable", "Análisis", "Operación", "Sistema AP",
     "Resultados de análisis de agua potable", "Análisis según frecuencia definida",
     PLAN_MANEJO, "DS 594", "Mensual",
     "Análisis vigentes conformes", "Revisión de informes de laboratorio", "Resultados conformes",
     "Exigencia legal o reglamentaria", "Norma o permiso aplicable", 1),
    ("REQ-042", "Fosas sépticas", "Mantención", "Operación", "Sanitarios",
     "Limpieza y mantención de fosas sépticas", "Limpieza mensual registrada",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Registro de limpieza mensual", "Revisión de certificados", "Limpieza al día",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-043", "Baños químicos", "Limpieza", "Operación", "Sanitarios",
     "Limpieza semanal de baños químicos", "Limpieza semanal con registro",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Registro semanal completo", "Revisión de registros", "Limpieza semanal cumplida",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-044", "Protección del agua", "Desgrasadoras", "Operación", "Comedor/taller",
     "Condiciones de cámaras desgrasadoras", "Cámaras operativas y mantenidas",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Cámaras limpias y funcionales", "Inspección visual", "Desgrasadoras conformes",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-045", "Protección del agua", "Descargas", "Operación", "Instalación completa",
     "Ausencia de descargas no autorizadas", "Sin vertidos fuera de sistemas autorizados",
     PLAN_MANEJO, "Ley 19.300 / Código de Aguas", "Semanal",
     "Sin descargas visibles", "Inspección visual", "Sin descargas no autorizadas",
     "Exigencia legal o reglamentaria", "Norma o permiso aplicable", 1),
    ("REQ-046", "Río Ventisquero", "Prohibiciones", "Operación", "Perímetro río",
     "Prohibición lavado de camiones/maquinaria cerca del río", "Sin lavado en sector río",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Sin lavado en sector", "Inspección visual", "Prohibición cumplida",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-047", "Río Ventisquero", "Residuos líquidos", "Operación", "Perímetro río",
     "Ausencia contacto residuos líquidos con cauces", "Sin contacto con cauce",
     PLAN_MANEJO, "Código de Aguas", "Semanal",
     "Sin contacto con cauce", "Inspección visual", "Protección del cauce",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-048", "Residuos domiciliarios y asimilables", "Contenedores", "Operación", "Sectores de residuos",
     "Contenedores herméticos con tapa", "Contenedores cerrados y en buen estado",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Contenedores conformes", "Inspección visual", "Contenedores operativos",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-049", "Segregación de residuos", "Rotulación", "Operación", "Puntos de segregación",
     "Rotulación y segregación de residuos", "Residuos segregados y rotulados",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Segregación visible", "Inspección visual", "Segregación conforme",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-050", "Residuos domiciliarios y asimilables", "Retiro", "Operación", "Sectores de residuos",
     "Frecuencia de retiro de residuos domiciliarios", "Retiro según frecuencia definida",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Retiros registrados", "Revisión de registros", "Frecuencia cumplida",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-051", "Transporte y disposición final", "Disposición", "Operación", "Residuos domiciliarios",
     "Disposición final en vertedero autorizado (La Junta u otro)", "Certificados de disposición",
     PLAN_MANEJO, "Validar con normativa vigente o autoridad competente", "Mensual",
     "Certificados del mes", "Revisión documental", "Disposición autorizada acreditada",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-052", "Control de plagas", "Vectores", "Operación", "Instalación completa",
     "Control de vectores", "Sin proliferación de vectores",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Control efectivo", "Inspección visual", "Vectores controlados",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-053", "Residuos domiciliarios y asimilables", "Acumulación", "Operación", "Instalación completa",
     "Ausencia de acumulación de residuos", "Sin acopios fuera de sectores habilitados",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Sin acumulación", "Inspección visual", "Instalación sin acumulación",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-054", "Declaración RCD", "Reporte mensual", "Operación", "Oficina ambiental",
     "Reporte mensual Planilla RCD", "RCD reportado mensualmente",
     PLAN_MANEJO, "Validar con normativa vigente o autoridad competente", "Mensual",
     "Planilla RCD del mes", "Revisión documental", "RCD reportado",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-055", "Bodega RESPEL", "Infraestructura", "Operación", "Bodega RESPEL",
     "Bodega RESPEL con radier impermeable", "Piso impermeabilizado y drenaje controlado",
     PLAN_MANEJO, "DS 148", "Mensual",
     "Radier conforme", "Inspección visual", "Infraestructura conforme",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-056", "Bodega RESPEL", "Señalización", "Operación", "Bodega RESPEL",
     "Señalización de bodega RESPEL", "Señalética RESPEL visible",
     PLAN_MANEJO, "DS 148", "Mensual",
     "Señalización conforme", "Inspección visual", "Señalización operativa",
     "Exigencia legal o reglamentaria", "Norma o permiso aplicable", 1),
    ("REQ-057", "Residuos peligrosos", "Almacenamiento", "Operación", "Bodega RESPEL",
     "Compatibilidad y contenedores cerrados etiquetados", "Almacenamiento compatible y rotulado",
     PLAN_MANEJO, "DS 148", "Semanal",
     "Contenedores cerrados y etiquetados", "Inspección visual", "Almacenamiento conforme",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-058", "Residuos peligrosos", "Registro", "Operación", "Bodega RESPEL",
     "Registro de ingreso y salida RESPEL", "Libro o registro actualizado",
     PLAN_MANEJO, "DS 148", "Mensual",
     "Registro completo", "Revisión documental", "Trazabilidad RESPEL",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-059", "Residuos peligrosos", "Tiempo almacenamiento", "Operación", "Bodega RESPEL",
     "Tiempo de almacenamiento ≤ 6 meses", "Sin RESPEL almacenado por más de 6 meses",
     PLAN_MANEJO, "DS 148", "Mensual",
     "Antigüedad ≤ 6 meses", "Revisión de registro", "Plazo de almacenamiento cumplido",
     "Exigencia legal o reglamentaria", "Norma o permiso aplicable", 1),
    ("REQ-060", "Transporte y disposición final", "RESPEL", "Operación", "Bodega RESPEL",
     "Transporte y disposición RESPEL autorizados", "Manifiestos y certificados de disposición",
     PLAN_MANEJO, "DS 148", "Mensual",
     "Manifiestos del mes", "Revisión documental", "Disposición RESPEL acreditada",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-061", "Residuos peligrosos", "Aceites y filtros", "Operación", "Taller/bodega",
     "Control de aceites usados, filtros, baterías y similares", "RESPEL segregados y gestionados",
     PLAN_MANEJO, "DS 148", "Mensual",
     "RESPEL identificados y gestionados", "Inspección y revisión registros", "Gestión conforme",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-062", "Orden y limpieza", "General", "Operación", "Instalación completa",
     "Orden general de la instalación", "Instalación ordenada y limpia",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Orden y limpieza general", "Inspección visual", "Instalación ordenada",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-063", "Control de accesos", "Perímetro", "Operación", "Acceso principal",
     "Cierre perimetral y portón cerrado", "Perímetro cerrado con control de acceso",
     PLAN_MANEJO, PLAN_MANEJO, "Diaria",
     "Portón y cerco operativos", "Inspección visual", "Acceso controlado",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-064", "Ocupación del área", "Faja fiscal", "Operación", "Perímetro",
     "Ausencia de acopios en faja fiscal", "Sin materiales en faja fiscal",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Faja fiscal libre", "Inspección visual", "Sin acopios en faja fiscal",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-065", "Flujo y tránsito de maquinaria", "Ruta 7", "Operación", "Acceso Ruta 7",
     "Ausencia de camiones/maquinaria estacionados en Ruta 7", "Estacionamiento solo en instalación",
     PLAN_MANEJO, PLAN_MANEJO, "Semanal",
     "Sin estacionamiento en ruta", "Inspección visual", "Cumplimiento verificado",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-066", "Señalización", "Interna", "Operación", "Instalación completa",
     "Señalización interna y de velocidad", "Señalética visible y mantenida",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Señalización operativa", "Inspección visual", "Señalización conforme",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-067", "Condiciones generales de operación", "Instalaciones", "Operación", "Bodegas/oficinas/comedor",
     "Estado de bodegas, oficinas, comedor, laboratorio y taller", "Instalaciones en condiciones higiénicas",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Instalaciones conformes", "Inspección visual", "Condiciones adecuadas",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-068", "Condiciones generales de operación", "Quemas", "Operación", "Instalación completa",
     "Ausencia de quemas al aire libre", "Prohibición de quemas cumplida",
     PLAN_MANEJO, "Ley 19.300 / DS 12", "Semanal",
     "Sin quemas", "Inspección visual", "Sin quemas detectadas",
     "Exigencia legal o reglamentaria", "Norma o permiso aplicable", 1),
    ("REQ-069", "Flora y fauna", "Prohibición caza", "Operación", "Instalación completa",
     "Prohibición de cazar", "Personal inducido y cumplimiento verificado",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Sin evidencia de caza", "Inducción y observación", "Prohibición cumplida",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-070", "Prohibición de caza y alimentación de fauna", "Alimentación fauna", "Operación", "Instalación completa",
     "Prohibición de alimentar fauna", "Sin alimentación de fauna silvestre",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Sin alimentación de fauna", "Inspección e inducción", "Prohibición cumplida",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-071", "Flora y fauna", "Flora", "Operación", "Perímetro instalación",
     "Prohibición de afectar flora sin autorización", "Sin intervención fuera del área autorizada",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Sin afectación no autorizada", "Inspección visual", "Flora protegida",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-072", "Patrimonio arqueológico", "Hallazgos", "Operación", "Instalación completa",
     "Ausencia de hallazgos arqueológicos o gestión conforme", "Procedimiento ante hallazgos disponible",
     PLAN_MANEJO, "Ley 17.288 / CMN", "Mensual",
     "Sin hallazgos o gestión conforme", "Inspección y revisión procedimiento", "Patrimonio protegido",
     "Exigencia legal o reglamentaria", "Norma o permiso aplicable", 1),
    ("REQ-073", "Capacitación e inducción ambiental", "Inducción", "Operación", "Instalación completa",
     "Registro de inducción al personal", "Personal inducido en materias ambientales",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Listas de asistencia vigentes", "Revisión documental", "Inducciones registradas",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-074", "Río Ventisquero", "Entorno", "Operación", "Perímetro río",
     "Protección del entorno del río Ventisquero", "Buenas prácticas en zona de interés turístico",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Entorno protegido", "Inspección visual", "Protección del entorno",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-075", "Relaciones con la comunidad", "Inducción", "Operación", "Instalación completa",
     "Inducción buenas prácticas con la comunidad", "Personal inducido en relación comunitaria",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Inducción realizada", "Revisión listas de asistencia", "Inducción comunitaria cumplida",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-076", "Relaciones con la comunidad", "Vecinos", "Operación", "Acceso/Puyuhuapi",
     "Respeto a vecinos y residentes de Puyuhuapi", "Conducta respetuosa del personal",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Sin conflictos registrados", "Revisión de reclamos", "Relación respetuosa",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-077", "Relaciones con la comunidad", "Turismo", "Operación", "Acceso Queulat",
     "Respeto a visitantes Parque Nacional Queulat", "Conducta respetuosa en vías de acceso",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Sin incidentes con visitantes", "Revisión de reclamos", "Buenas prácticas turísticas",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-078", "Relaciones con la comunidad", "Reclamos", "Operación", "Comunidad",
     "Registro de reclamos y respuestas comunitarias", "Reclamos registrados y respondidos",
     PLAN_MANEJO, PLAN_MANEJO, "Mensual",
     "Registro de reclamos actualizado", "Revisión documental", "Reclamos gestionados",
     "Obligación contenida en el Plan de Manejo", "Derivado del Plan de Manejo", 1),
    ("REQ-079", "Contratación de mano de obra local", "Empleo local", "Operación", "RRHH",
     "Contratación de mano de obra local cuando corresponda", "Cumplimiento de compromiso de empleo local",
     PLAN_MANEJO, "Bases contractuales", "Mensual",
     "Registro de contrataciones locales", "Revisión documental", "Compromiso verificado",
     "Compromiso contractual", "Requiere validación", 1),
    ("REQ-080", "ZOIT Aysén Patagonia Queulat", "Cumplimiento ZOIT", "Operación", "Instalación completa",
     "Cumplimiento disposiciones ZOIT cuando aplique", "Actividades conforme a zona de interés turístico",
     PLAN_MANEJO, "Validar con normativa vigente o autoridad competente", "Mensual",
     "Sin infracciones ZOIT", "Revisión normativa y observación", "Cumplimiento ZOIT",
     "Exigencia legal o reglamentaria", "Requiere validación", 1),
    ("REQ-081", "Abandono y cierre de la instalación", "Retiro instalaciones", "Cierre", "Instalación completa",
     "Retiro de instalaciones al cierre", "Cuando corresponda, retiro conforme al PMA",
     PLAN_MANEJO, PLAN_MANEJO, "Eventual",
     "Retiro conforme plan de cierre", "Inspección visual", "Cierre progresivo conforme",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-082", "Abandono y cierre de la instalación", "Restitución terreno", "Cierre", "Terreno 1,6 ha",
     "Nivelación y restitución del terreno", "Terreno restituido según compromiso",
     PLAN_MANEJO, PLAN_MANEJO, "Eventual",
     "Restitución conforme", "Inspección y acta", "Terreno restituido",
     "Obligación contenida en el Plan de Manejo", "Expreso en el Plan de Manejo", 1),
    ("REQ-083", "Abandono y cierre de la instalación", "Informe cierre", "Cierre", "Oficina ambiental",
     "Entrega informe de cierre al Inspector Fiscal", "Informe de cierre elaborado y entregado",
     PLAN_MANEJO, "Bases contractuales", "Eventual",
     "Informe entregado con folio", "Revisión documental", "Cierre documentado",
     "Compromiso contractual", "Derivado del Plan de Manejo", 1),
]

DOCUMENTOS_BASE = [
    ("DOC-001", "Permiso/Aprobación", "Plan de Manejo Instalación de Faenas Rev. 1", "Ambiental",
     "Validar con autoridad competente", EMPRESA, "Validar número", "01-05-2026", "01-05-2028",
     "Encargado ambiental", "Oficina ambiental / digital"),
    ("DOC-002", "Permiso/Aprobación", "Sistema de agua potable particular", "Sanitaria",
     "SEREMI Salud Aysén", EMPRESA, "Validar número", "01-05-2026", "01-05-2028",
     "Encargado ambiental", "Oficina ambiental"),
    ("DOC-003", "Permiso/Aprobación", "Sistema de alcantarillado particular", "Sanitaria",
     "SEREMI Salud Aysén", EMPRESA, "Validar número", "01-05-2026", "01-05-2028",
     "Encargado ambiental", "Oficina ambiental"),
    ("DOC-004", "Permiso/Aprobación", "Autorización bodega RESPEL", "Ambiental/RESPEL",
     "Validar con autoridad competente", EMPRESA, "Validar número", "01-05-2026", "01-05-2028",
     "Encargado ambiental", "Bodega RESPEL"),
    ("DOC-005", "Resolución sanitaria", "Control de plagas", "Sanitaria",
     "SEREMI Salud", "Empresa prestadora", "Validar número", "01-05-2026", "01-05-2028",
     "Encargado ambiental", "Oficina ambiental"),
    ("DOC-006", "Certificado", "Limpieza baños químicos y fosas sépticas", "Sanitaria",
     "SEREMI Salud", "Empresa prestadora", "Validar número", "01-05-2026", "01-05-2028",
     "Encargado ambiental", "Oficina ambiental"),
    ("DOC-007", "Certificado", "Análisis agua potable", "Sanitaria",
     "Laboratorio autorizado", EMPRESA, "Validar número", "01-05-2026", "31-05-2026",
     "Encargado ambiental", "Laboratorio / digital"),
    ("DOC-008", "Permiso", "Transporte RESPEL", "Ambiental",
     "Validar con autoridad competente", "Transportista RESPEL", "Validar número", "01-05-2026", "01-05-2028",
     "Encargado ambiental", "Bodega RESPEL"),
    ("DOC-009", "Declaración", "Declaración anual emisiones RETC", "Atmosférica",
     "MMA / RETC", EMPRESA, "Validar folio", "01-01-2027", "30-04-2027",
     "Encargado ambiental", "RETC / digital"),
    ("DOC-010", "Certificado", "Disposición final residuos domiciliarios", "Residuos",
     "Vertedero autorizado", "Empresa transportista", "Validar número", "01-05-2026", "31-05-2026",
     "Encargado ambiental", "Oficina ambiental"),
]

TEMAS_CAPACITACION = [
    "Buenas prácticas ambientales", "Manejo de residuos", "Residuos peligrosos",
    "Control de derrames", "Protección del agua", "Protección del río Ventisquero",
    "Flora y fauna", "Prohibición de caza y alimentación de fauna",
    "Patrimonio arqueológico", "Relación con la comunidad", "Control de velocidad",
    "Uso de hojas de seguridad", "Procedimiento ante emergencias ambientales",
]

MESES_AUDITORIA = [
    "05-2026", "06-2026", "07-2026", "08-2026", "09-2026", "10-2026",
    "11-2026", "12-2026", "01-2027", "02-2027", "03-2027", "04-2027",
    "05-2027", "06-2027", "07-2027", "08-2027", "09-2027", "10-2027",
    "11-2027", "12-2027", "01-2028", "02-2028", "03-2028", "04-2028", "05-2028",
]
